#!/usr/bin/env python3
"""E31 generator: extract every ```luau fence from the skill files verbatim into blocks/,
then build run-<id>.luau (mock, --!nocheck, harness prologue + body + tails/<id>.luau) and
strict-<id>.luau (skill §1.1 prologue with relative requires + body). Hand-written walkthrough
bodies (ui-*.body.luau) go through the same wrapper. Usage: python3 gen.py [--extract]"""
import os, re, sys, glob
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "../../.."))
SK = os.path.join(ROOT, "docs/skills/quad-ui-dev")
FILES = {"skill": "SKILL.md", "recipes": "references/code-recipes.md",
         "rules": "references/rules-and-invariants.md"}

MOCK = """--!nocheck
-- GENERATED by gen.py (mock runner) — body below the marker is verbatim.
local H = require("./harness")
local q = H.q
local D = q.Declaration
local mock = require("../../../quad-base/test/mock")
local QuadTypes = require("../../../quad-types/src")
local DeclarationModule = require("../../../quad-roblox/src/Declaration")
UDim2 = H.EG.UDim2; Color3 = H.EG.Color3; Enum = H.EG.Enum; Vector2 = H.EG.Vector2; UDim = H.EG.UDim; Font = H.EG.Font
-- ===== body =====
"""
STRICT = """--!strict
-- GENERATED by gen.py (strict check) — prologue = SKILL.md §1.1 with the three placeholders
-- replaced by relative paths to the source tree; body below the marker is verbatim.
-- ONE installed set (quad-roblox/luau_packages after relink.sh) — mixing quad-base/src with a
-- different quad_types file breaks generic inference (probe-req2/3 vs probe-req1; see README).
local Quad = require("../../../quad-roblox/luau_packages/quad_base")
local QuadRoblox = require("../../../quad-roblox/src").QuadRoblox
local QuadTypes = require("../../../quad-roblox/luau_packages/quad_types")
local q = Quad:UseProvider(QuadRoblox)
local D = q.Declaration
{extra}-- ===== body =====
"""

def extract():
    for tag, rel in FILES.items():
        lines = open(os.path.join(SK, rel)).read().split("\n")
        inb = False
        for i, l in enumerate(lines, 1):
            if l.startswith("```"):
                if not inb:
                    inb, start, lang, buf = True, i, l[3:].strip(), []
                else:
                    inb = False
                    if lang == "luau":
                        name = f"{tag}-L{start}"
                        with open(os.path.join(HERE, "blocks", name + ".body.luau"), "w") as f:
                            f.write(f"-- source: {rel}:{start}-{i}\n" + "\n".join(buf) + "\n")
            elif inb:
                buf.append(l)

def build():
    for p in sorted(glob.glob(os.path.join(HERE, "blocks", "*.body.luau"))):
        name = os.path.basename(p)[: -len(".body.luau")]
        if name in ("skill-L73", "recipes-L6"):
            continue  # prologue with <placeholder> requires — reproduced by the STRICT header itself
        body = open(p).read()
        # a chunk-final `return X` would end the chunk before the mock tail
        mbody = re.sub(r"\n(return \w+)\s*$", r"\n-- (mock: stripped `\1`)\n", body)
        tailp = os.path.join(HERE, "tails", name + ".luau")
        tail = open(tailp).read() if os.path.exists(tailp) else ""
        with open(os.path.join(HERE, f"run-{name}.luau"), "w") as f:
            f.write(MOCK + mbody + "\n-- ===== mock tail =====\n" + tail)
        extra = ""
        if "DeclarationModule" in body and "local DeclarationModule" not in body:
            extra = 'local DeclarationModule = require("../../../quad-roblox/src/Declaration") -- NOT in the skill prologue (gap)\n'
        with open(os.path.join(HERE, f"strict-{name}.luau"), "w") as f:
            f.write(STRICT.replace("{extra}", extra) + body)

if "--extract" in sys.argv:
    extract()
build()
