#!/usr/bin/env python3
"""E33: turn extracted doc signatures into a --!strict bidirectional-assignability probe.
For each doc member `Name: DocType` we emit, inside a generic probe function,
    type D<n> = DocType
    local _a<n>: D<n> = ACTUAL                           -- actual <: doc  (doc not narrower)
    local function _b<n>(d: D<n>) local _: typeof(ACTUAL) = d end   -- doc <: actual (doc not wider)
and for each `export type X = ...` in a doc block the same against the real alias.
Output: probe_sigs.luau + probe_map.json (line -> item id)."""
import json, re
recs = json.load(open("extracted.json"))

# Items not auto-checkable (abbreviated / placeholder names) — judged statically in README.
SKIP_MEMBER = {
    (70, "As<Class>"), (78, None), (119, None), (101, None),
}
def actual_for(rid, rec, name):
    h = rec["heading"] or ""
    f = rec["file"]
    m = re.match(r"`q\.(\w+)(?:\.(\w+))?", h)
    if h.startswith("`q:"): return f"q.{name}"
    if rid == 117: return "QRmod.QuadRoblox"
    if rid == 118: return "q.UseProvider"
    if rid in (119,):
        return {"D.Frame": "q.Declaration.Frame"}.get(name)
    if rid == 120: return "q.Declaration.New"
    if rid == 121: return {"D.Modifier.Frame": "q.Declaration.Modifier.Frame"}.get(name)
    if rid == 122: return {"Size": "fm.Size"}.get(name)
    if rid == 123: return {"AsFrame": "gm.AsFrame", "AsTextLabel": "gm.AsTextLabel", "AsGuiObject": "gm.AsGuiObject"}.get(name)
    if rid == 125: return {"D.Mapper.Frame": "q.Declaration.Mapper.Frame"}.get(name)
    if rid == 126: return {"newMapperClass": "q.newMapperClass", "MapperRoot": "q.MapperRoot"}.get(name)
    if rid == 81: return "getmetatable(q.Attr).__call" if name == "__call" else None
    if rid == 102: return f"q.Dispatch.{name}"
    if rid == 133: return "q.Context"
    if rid == 130: return "tw.Mapped"
    if rid == 131: return "q.isTween"
    recv = {
        "source": "src", "state": "st", "store": "sto", "observer": "ob", "effect": "ef",
        "slot": "sl", "ref": "rf", "mod": "md", "tag": "tg", "attr": "at", "ctx": "cx",
        "provider": "pv", "handle": "gh", "blocker": "bl", "tween": "tw",
    }
    m2 = re.match(r"`(\w+)[:.](\w+)", h)
    if m2 and m2.group(1) in recv:
        return f"{recv[m2.group(1)]}.{name}"
    if m:
        a, b = m.group(1), m.group(2)
        if b: return f"q.{a}.{name}"
        if name == a or name.startswith(a): return f"q.{name}"
        return f"q.{name}"
    if f.startswith("extend/02"):
        return f"q.Dispatch.{name}"
    return None

REAL_TYPE = {  # doc alias name -> real alias
    "Source": "QT.Source<number>", "ObserverFn": "QT.ObserverFn<number>", "Observer": "QT.Observer",
    "GateEmit": "QT.GateEmit", "GateSetup": "QT.GateSetup", "Store": "QT.Store<{ x: number }>",
    "EffectFn": "QT.EffectFn", "Effect": "QT.Effect", "SlotListOpts": "QT.SlotListOpts",
    "FieldOut": "QT.FieldOut<number>", "AttrKeyObject": "QT.AttrKeyObject", "AttrSugar": "QT.AttrSugar<number>",
    "None": "QT.None", "Detach": "QT.Detach", "KeyGone": "QT.KeyGone", "MapperRoot": "QT.MapperRoot",
    "Handler": "QT.Handler", "FieldV": "DM.FieldV<number>", "Field": "DM.Field<number>",
    "OnChangeFn": "DM.OnChangeFn", "OnChangeDescriptor": "DM.OnChangeDescriptor<\"Size\">", "OutFn": "QRmod.OutFn",
    "TweenConstructor": "QRT.TweenConstructor", "TweenOverride": "QRT.TweenOverride",
    "TweenOptions": "QRT.TweenOptions<number>", "AnimateFn": "QRT.AnimateFn", "AnimateInfo": "QRT.AnimateInfo",
    "ContextConstructor": "QT.ContextConstructor", "Provider": "QT.Provider<number>",
    "DebounceOptions": "QT.DebounceOptions", "ThrottleOptions": "QT.ThrottleOptions", "TimedGate": "QT.TimedGate",
    "Blocker": "QT.Blocker", "Relate": "QT.Relate", "Namespace": "QT.ErrorNamespace",
}
INST = {"T": "number", "K": "\"Size\""}
INST_BY = {"Store": "{ x: number }"}

from common import parse_block
lines = ["--!strict", "-- GENERATED by gen_probe.py (E33) — do not edit", 
 'local QT = require("../../../quad-roblox/luau_packages/quad_types")',
 'local QRmod = require("../../../quad-roblox/src")',
 'local DM = require("../../../quad-roblox/src/Declaration")',
 'local QRT = require("../../../quad-roblox/src/types")',
 "type QR_OutFn = QRmod.OutFn",
 "type RobloxExtension = QRmod.RobloxExtension",
 "type FieldV<T> = DM.FieldV<T>",
 "type OnChangeDescriptor<K> = DM.OnChangeDescriptor<K>",
]
# alias every QT export used by docs
names = ["StateMarker","SlotMarker","TagMarker","TagNames","AttrMarker","Detach","KeyGone","None","MapperDescriptor","MapperRoot",
 "ErrorNamespace","Epoch","EpochSet","Relate","StripNil","RefCallback","Ref","PreRef","PostRef","StateData","FieldOut","State","Source",
 "Observer","ObserverFn","Effect","EffectFn","GateEmit","GateSetup","Blocker","GateHandle","DebounceOptions","ThrottleOptions",
 "TimedGate","Provider","Context","ContextConstructor","NumArg","NumOp","TagIter","Tag","Attr","AttrKeyObject","AttrSugar","Modifier",
 "Handler","Store","SlotElement","SlotItem","SlotListOpts","Slot","Quad","CheckReservedKeys"]
generic = {"StateMarker":"T","SlotMarker":"T","StripNil":"T","RefCallback":"T","Ref":"T","PreRef":"T","PostRef":"T","StateData":"T",
 "FieldOut":"T","State":"T","Source":"T","ObserverFn":"T","Provider":"T","AttrSugar":"T","Store":"T","SlotElement":"T","SlotItem":"T","Slot":"T","CheckReservedKeys":"T"}
for n in names:
    if n in generic: lines.append(f"type {n}<T> = QT.{n}<T>")
    else: lines.append(f"type {n} = QT.{n}")
for n in ["Tween","TweenData","TweenOptions"]:
    lines.append(f"type {n}<T> = QRT.{n}<T>")
for n in ["TweenOverride","AnimateInfo"]:
    lines.append(f"type {n} = QRT.{n}")
for n in ["FrameModifier","TextLabelModifier","GuiObjectModifier","FrameElem","FrameMapperElem","PropTypesRead"]:
    lines.append(f"type {n} = DM.{n}")
lines.append("type FrameParam<E> = DM.FrameParam<E>")
lines.append("type Field<T> = DM.Field<T>")
lines.append("local q: Quad & QRmod.RobloxExtension = nil :: any")
lines.append("local _ = q")
lines.append("local function _probe<T>(src: Source<T>, st: State<T>, sto: Store<{}>, ob: Observer, ef: Effect, sl: Slot<T>, rf: Ref<T>, md: Modifier, tg: Tag, at: Attr, cx: Context, pv: Provider<T>, gh: GateHandle, bl: Blocker, tw: Tween<T>, fm: FrameModifier, gm: GuiObjectModifier)")
pmap = {}; n = 0; skipped = []
for rid, r in enumerate(recs):
    try:
        items = parse_block(r["sig"])
    except Exception as e:
        skipped.append((rid, "parse", str(e))); continue
    if not items: skipped.append((rid, "noitems", r["sig"][:60])); continue
    for kind, name, params, text in items:
        text = text.strip()
        if "…" in text or "<Class>" in name or "<Ancestor>" in text:
            skipped.append((rid, "abbrev", name)); continue
        n += 1
        if kind == "member":
            act = actual_for(rid, r, name)
            if act is None: skipped.append((rid, "noactual", name)); continue
            lines.append(f"\tdo -- [{rid}] {r['file']}:{r['line']} {name}")
            s = len(lines)
            lines.append(f"\t\ttype D{n} = {text}")
            for extra in text.split("\n")[1:]: pass
            lines.append(f"\t\tlocal _a{n}: D{n} = {act} -- ACTUAL<:DOC")
            lines.append(f"\t\tlocal function _b{n}(d: D{n}) local _: typeof({act}) = d end -- DOC<:ACTUAL")
            lines.append("\tend")
            e = len(lines)
            for ln in range(s, e + text.count("\n") + 1): pmap[ln] = f"{rid}|{name}"
        else:
            real = REAL_TYPE.get(name)
            if real is None: skipped.append((rid, "notype", name)); continue
            inst = ""
            if params:
                ps = [p.strip() for p in params.strip("<>").split(",")]
                inst = "<" + ", ".join(INST_BY.get(name) or INST.get(p, "number") for p in ps) + ">"
            lines.append(f"\tdo -- [{rid}] {r['file']}:{r['line']} type {name}")
            s = len(lines)
            lines.append(f"\t\ttype X{n}{params or ''} = {text}")
            lines.append(f"\t\tlocal function _c{n}(d: X{n}{inst}) local _: {real} = d end -- DOC<:REAL")
            lines.append(f"\t\tlocal function _d{n}(d: {real}) local _: X{n}{inst} = d end -- REAL<:DOC")
            lines.append("\tend")
            e = len(lines)
            for ln in range(s, e + text.count("\n") + 1): pmap[ln] = f"{rid}|{name}"
# negative controls (must each produce a TypeError, proving the probe is live at the end of the file)
lines.append("\tdo -- NEGCTL1 method in generic context")
lines.append("\t\ttype N1 = (self: Slot<T>, index: string) -> ()")
lines.append("\t\tlocal _n1: N1 = sl.Remove -- NEGCTL1")
lines.append("\tend")
lines.append("\tdo -- NEGCTL2 record alias")
lines.append("\t\tlocal function _n2(d: QT.Blocker) local _: { read Blocking: number } = d end -- NEGCTL2")
lines.append("\tend")
lines.append("\tdo -- NEGCTL3 roblox surface")
lines.append("\t\tlocal _n3: (x: any) -> number = q.isTween -- NEGCTL3")
lines.append("\tend")
lines.append("end")
lines.append("return _probe")
# expand multi-line text: lines list entries may contain \n
final = []
lm = {}
for i, l in enumerate(lines, 1):
    parts = l.split("\n")
    for p in parts:
        final.append(p)
        if i in pmap: lm[len(final)] = pmap[i]
open("probe_sigs.luau", "w").write("\n".join(final) + "\n")
json.dump({"lines": lm, "skipped": skipped}, open("probe_map.json", "w"), indent=1, ensure_ascii=False)
print("items", n, "skipped", len(skipped))
for s in skipped: print(" skip", s)
