#!/usr/bin/env python3
"""E58: generate mock/<key>.luau and strict/<key>.luau from blocks/ + spec.py"""
import re, pathlib
here = pathlib.Path(__file__).parent
exec(open(here / "spec.py").read())
idx = [l.rstrip("\n").split("\t") for l in open(here / "index.tsv")]
# page prologue = first block of the page that contains a require
prolog = {}
for f, s, n, name in idx:
    body = (here / "blocks" / name).read_text()
    if f not in prolog and "require(" in body:
        prolog[f] = (name, body)
REQ = [
    (r'require\("@game/ReplicatedStorage/Client/UI/Quad"\)', 'require("./Quad")'),
    (r'require\("@game/ReplicatedStorage/roblox_packages/quad_types"\)', 'require("../../../../quad-roblox/luau_packages/quad_types")'),
    (r'require\("@game/ReplicatedStorage/roblox_packages/quad_base"\)', 'require("../../../../quad-roblox/luau_packages/quad_base")'),
    (r'require\("@game/ReplicatedStorage/roblox_packages/quad_roblox"\)', 'require("../../../../quad-roblox/src")'),
    (r'require\(<quad-roblox 모듈>\)', 'require("../../../../quad-roblox/src") --[[E58: 문서의 자리표시 <quad-roblox 모듈>]]'),
]
MOCK_PRO = '''--!nocheck
-- E58 mock runner (generated by gen.py) — {key}
local H = require("../harness")
local q, D, Quad, QuadRoblox = H.q, H.D, H.Quad, H.QuadRoblox
local QuadTypes, RobloxModule = {{}}, {{}} -- type-only in docs
local M = D.Mapper
local Op = q.Operator
local EG = H.EG
local UDim2, UDim, Color3, Enum, Vector2, Font = EG.UDim2, EG.UDim, EG.Color3, EG.Enum, EG.Vector2, EG.Font
local task = H.task
local warn = function(...) print("[warn]", ...) end
local script = {{ Parent = nil }}
local game = H.game
'''
kinds = {}
for f, s, n, name in idx:
    key = name[:-5]
    sp = S.get(key)
    if sp is None:
        continue
    body = (here / "blocks" / name).read_text()
    pre = sp.get("pre", "")
    post = sp.get("post", "")
    mbody = body
    for old, new in sp.get("sub", []):
        assert old in mbody, (key, old)
        mbody = mbody.replace(old, "--[[E58 보강]] " + new, 1)
    # mock: body; page prologue type lines (`type State<T> = q.State<T>`) harmless but strip requires
    mp = MOCK_PRO.format(key=key)
    mbody = re.sub(r'^(local \w+ = )require\(.*$', r'\1(nil) --[[E58: require stripped]]', mbody, flags=re.M)
    txt = mp + (f"--[[E58 보강 pre]]\n{pre}\n" if pre else "") + f"-- ==== doc block {f}:{s} ====\n" + mbody + (f"-- ==== E58 보강 post ====\n{post}\n" if post else "") + 'print("<<END>>")\n'
    # a doc block may redefine the page prologue (roblox-style); fine at runtime except `require`
    (here / "mock" / f"{key}.luau").write_text(txt)
    if sp.get("skip"):
        continue
    pname, ptxt = prolog[f]
    ptxt2 = ptxt
    for a_, b_ in REQ:
        ptxt2 = re.sub(a_, b_, ptxt2)
    stxt = f"--!strict\n-- E58 strict (generated) — {key}\n-- ==== page prologue {f} ({pname}) ====\n{ptxt2}" + (f"--[[E58 보강 pre]]\n{pre}\n" if pre else "") + f"-- ==== doc block {f}:{s} (line offset marker) ====\n"
    off = stxt.count("\n")
    bodyr = body
    for a_, b_ in REQ:
        bodyr = re.sub(a_, b_, bodyr)
    (here / "strict" / f"{key}.luau").write_text(stxt + bodyr)
    kinds[key] = off
(here / "strict-offsets.tsv").write_text("".join(f"{k}\t{v}\n" for k, v in kinds.items()))
print(len(list((here/"mock").glob("*.luau"))), "mock;", len(kinds), "strict")
