#!/usr/bin/env python3
"""E70: generate mock/<key>.luau and strict/<key>.luau from blocks/ + spec.py (E58 gen.py 확장: with/module/pre2/mpre/spre/ssub)"""
import re, pathlib
here = pathlib.Path(__file__).parent
exec(open(here / "spec.py").read())
idx = [l.rstrip("\n").split("\t") for l in open(here / "index.tsv")]
page = {n[:-5]: f for f, s, _, n in idx}
line = {n[:-5]: s for f, s, _, n in idx}
def body(k): return (here / "blocks" / f"{k}.luau").read_text()
REQ = [
    (r'require\("@game/ReplicatedStorage/Client/UI/Quad"\)', 'require("./Quad")'),
    (r'require\("@game/ReplicatedStorage/Client/UI/(\w+)"\)', r'require("./\1")'),
    (r'require\("@game/ReplicatedStorage/roblox_packages/quad_types"\)', 'require("../../../../quad-roblox/luau_packages/quad_types")'),
    (r'require\("@game/ReplicatedStorage/roblox_packages/quad_base"\)', 'require("../../../../quad-roblox/luau_packages/quad_base")'),
    (r'require\("@game/ReplicatedStorage/roblox_packages/quad_roblox"\)', 'require("../../../../quad-roblox/src")'),
    (r'require\("\.\./luau_packages/quad_base"\)', 'require("../../../../quad-roblox/luau_packages/quad_base")'),
]
def sreq(t):
    for a_, b_ in REQ: t = re.sub(a_, b_, t)
    return t
def mreq(t):
    t = re.sub(r'require\("(?:@game/ReplicatedStorage/Client/UI/|\./)Quad"\)', 'H.q', t)
    t = re.sub(r'require\("@game/ReplicatedStorage/roblox_packages/quad_types"\)', '{}', t)
    t = re.sub(r'require\("@game/ReplicatedStorage/roblox_packages/quad_roblox"\)', 'H.QuadRoblox', t)
    t = re.sub(r'require\("\.\./luau_packages/quad_base"\)', 'H.Quad.New()', t)
    t = re.sub(r'require\("(?:@game/ReplicatedStorage/Client/UI/|\./)(\w+)"\)', r'__mod_\1', t)
    return t
def wrap(name, t):
    t = re.sub(r'^export type', 'type', t, flags=re.M)
    return f"local __mod_{name} = (function()\n{t}\nend)()\n"
MOCK_PRO = '''--!nocheck
-- E70 mock runner (generated by gen.py) — {key}
local H = require("../harness")
local q, D, Quad, QuadRoblox = H.q, H.D, H.Quad, H.QuadRoblox
local QuadTypes, RobloxModule = {{}}, {{}} -- type-only in docs
local M = D.Mapper
local Op = q.Operator
local EG = H.EG
local UDim2, UDim, Color3, Enum, Vector2, Font = EG.UDim2, EG.UDim, EG.Color3, EG.Enum, EG.Vector2, EG.Font
local task = H.task
local warn = function(...) print("[warn]", ...) end
local script = {{ Parent = nil }}
local game = H.game
'''
MOCK_PRO_BASE = '''--!nocheck
-- E70 mock runner (base — Roblox 프로바이더 없는 새 quad_base 인스턴스) — {key}
local H = require("../harness")
local task = H.task
'''
def subs(t, lst, k):
    for old, new in lst:
        assert old in t, (k, old)
        t = t.replace(old, "--[[E70 보강]] " + new if not old.endswith("\n") else new, 1)
    return t
offs = []
for f, s, n, name in idx:
    k = name[:-5]; sp = S[k]
    if sp["cls"] in ("P", "b"): continue
    # ---- mock
    parts = []
    pk0 = PROLOG.get(f, "DEFAULT")
    if sp.get("mockpro") != "base":
        parts.append("-- ==== page prologue (mapped) ====\n" + (DEFAULT_PROLOG if pk0 == "DEFAULT" else ("" if pk0 is None else body(pk0))))
    mp = sp.get("mpre", sp.get("pre", ""))
    if mp: parts.append(f"--[[E70 보강 pre]]\n{mp}\n")
    for w in sp.get("with", []):
        wk, mod = (w if isinstance(w, tuple) else (w, None))
        wt = subs(body(wk), S[wk].get("ssub", []) + S[wk].get("sub", []), wk)
        parts.append(f"-- ==== with {page[wk]}:{line[wk]} ====\n" + (wrap(mod, wt) if mod else wt))
    mp2 = sp.get("mpre2", sp.get("pre2", ""))
    if mp2: parts.append(f"--[[E70 보강 pre2]]\n{mp2}\n")
    bt = subs(body(k), sp.get("ssub", []) + sp.get("sub", []), k)
    bt = wrap(sp["module"], bt) if sp.get("module") else bt
    parts.append(f"-- ==== doc block {f}:{s} ====\n{bt}")
    if sp.get("post"): parts.append(f"-- ==== E70 보강 post ====\n{sp['post']}\n")
    pro = (MOCK_PRO_BASE if sp.get("mockpro") == "base" else MOCK_PRO).format(key=k)
    (here / "mock" / f"{k}.luau").write_text(pro + mreq("".join(parts)) + 'print("<<END>>")\n')
    # ---- strict
    if sp.get("skip"): continue
    pk = PROLOG.get(f, "DEFAULT")
    pro = DEFAULT_PROLOG if pk == "DEFAULT" else ("" if pk is None else body(pk))
    hdr = f"--!strict\n-- E70 strict (generated) — {k}\nlocal H: any = nil -- [E70] mock 보강 식이 strict에서 any로 읽히게\n"
    st = hdr + (f"-- ==== page prologue ({pk}) ====\n{pro}" if pro else "")
    spp = sp.get("spre", sp.get("pre", ""))
    if spp: st += f"--[[E70 보강 pre]]\n{spp}\n"
    for w in sp.get("with", []):
        wk, mod = (w if isinstance(w, tuple) else (w, None))
        if mod: continue  # 모듈은 strict/<이름>.luau를 require로
        st += f"-- ==== with {page[wk]}:{line[wk]} ====\n" + subs(body(wk), S[wk].get("ssub", []), wk)
    sp2 = sp.get("spre2", sp.get("pre2", ""))
    if sp2: st += f"--[[E70 보강 pre2]]\n{sp2}\n"
    st += f"-- ==== doc block {f}:{s} ====\n"
    off = st.count("\n")
    bb = subs(body(k), sp.get("ssub", []), k)
    st = sreq(st + bb)
    fname = sp.get("module") or k
    (here / "strict" / f"{fname}.luau").write_text(st)
    offs.append((k, fname, off, off + bb.count("\n")))
(here / "strict-offsets.tsv").write_text("".join(f"{a}\t{b}\t{c}\t{d}\n" for a, b, c, d in offs))
print(len(list((here / "mock").glob("*.luau"))), "mock;", len(offs), "strict")
